package com.melissadata;

public class mdAddrJNI {
	static {
		try {
			System.loadLibrary("mdAddrJavaWrapper");
		} catch (UnsatisfiedLinkError ule) {
			System.out.println(ule);
			System.out.println("java.library.path="+System.getProperty("java.library.path"));
		}
	}

	public final static native long mdAddrCreate();
	public final static native void mdAddrDestroy(long I);
	public final static native int Initialize(long I,String p1,String p2,String p3);
	public final static native int InitializeDataFiles(long I);
	public final static native String GetInitializeErrorString(long I);
	public final static native boolean SetLicenseString(long I,String p1);
	public final static native String GetBuildNumber(long I);
	public final static native String GetDatabaseDate(long I);
	public final static native String GetExpirationDate(long I);
	public final static native String GetLicenseExpirationDate(long I);
	public final static native String GetCanadianDatabaseDate(long I);
	public final static native String GetCanadianExpirationDate(long I);
	public final static native void SetPathToUSFiles(long I,String p1);
	public final static native void SetPathToCanadaFiles(long I,String p1);
	public final static native void SetPathToDPVDataFiles(long I,String p1);
	public final static native void SetPathToLACSLinkDataFiles(long I,String p1);
	public final static native void SetPathToSuiteLinkDataFiles(long I,String p1);
	public final static native void SetPathToSuiteFinderDataFiles(long I,String p1);
	public final static native void SetPathToRBDIFiles(long I,String p1);
	public final static native String GetRBDIDatabaseDate(long I);
	public final static native void SetPathToAddrKeyDataFiles(long I,String p1);
	public final static native void ClearProperties(long I);
	public final static native void ResetDPV(long I);
	public final static native void SetCASSEnable(long I,int p1);
	public final static native void SetUseUSPSPreferredCityNames(long I,int p1);
	public final static native void SetDiacritics(long I,int p1);
	public final static native String GetStatusCode(long I);
	public final static native String GetErrorCode(long I);
	public final static native String GetErrorString(long I);
	public final static native String GetResults(long I);
	public final static native String GetResultCodeDescription(long I,String resultCode,int opt);
	public final static native void SetPS3553_B1_ProcessorName(long I,String p1);
	public final static native void SetPS3553_B4_ListName(long I,String p1);
	public final static native void SetPS3553_D3_Name(long I,String p1);
	public final static native void SetPS3553_D3_Company(long I,String p1);
	public final static native void SetPS3553_D3_Address(long I,String p1);
	public final static native void SetPS3553_D3_City(long I,String p1);
	public final static native void SetPS3553_D3_State(long I,String p1);
	public final static native void SetPS3553_D3_ZIP(long I,String p1);
	public final static native String GetFormPS3553(long I);
	public final static native boolean SaveFormPS3553(long I,String p1);
	public final static native void ResetFormPS3553(long I);
	public final static native void ResetFormPS3553Counter(long I);
	public final static native void SetStandardizationType(long I,int mode);
	public final static native void SetSuiteParseMode(long I,int mode);
	public final static native void SetAliasMode(long I,int mode);
	public final static native String GetFormSOA(long I);
	public final static native void SaveFormSOA(long I,String p1);
	public final static native void ResetFormSOA(long I);
	public final static native void SetSOACustomerInfo(long I,String customerName,String customerAddress);
	public final static native void SetSOACPCNumber(long I,String CPCNumber);
	public final static native String GetSOACustomerInfo(long I);
	public final static native String GetSOACPCNumber(long I);
	public final static native long GetSOATotalRecords(long I);
	public final static native float GetSOAAAPercentage(long I);
	public final static native String GetSOAAAExpiryDate(long I);
	public final static native String GetSOASoftwareInfo(long I);
	public final static native String GetSOAErrorString(long I);
	public final static native void SetCompany(long I,String p1);
	public final static native void SetLastName(long I,String p1);
	public final static native void SetAddress(long I,String p1);
	public final static native void SetAddress2(long I,String p1);
	public final static native void SetLastLine(long I,String p1);
	public final static native void SetSuite(long I,String p1);
	public final static native void SetCity(long I,String p1);
	public final static native void SetState(long I,String p1);
	public final static native void SetZip(long I,String p1);
	public final static native void SetPlus4(long I,String p1);
	public final static native void SetUrbanization(long I,String p1);
	public final static native void SetParsedAddressRange(long I,String p1);
	public final static native void SetParsedPreDirection(long I,String p1);
	public final static native void SetParsedStreetName(long I,String p1);
	public final static native void SetParsedSuffix(long I,String p1);
	public final static native void SetParsedPostDirection(long I,String p1);
	public final static native void SetParsedSuiteName(long I,String p1);
	public final static native void SetParsedSuiteRange(long I,String p1);
	public final static native void SetParsedRouteService(long I,String p1);
	public final static native void SetParsedLockBox(long I,String p1);
	public final static native void SetParsedDeliveryInstallation(long I,String p1);
	public final static native void SetCountryCode(long I,String p1);
	public final static native boolean VerifyAddress(long I);
	public final static native String GetCompany(long I);
	public final static native String GetLastName(long I);
	public final static native String GetAddress(long I);
	public final static native String GetAddress2(long I);
	public final static native String GetSuite(long I);
	public final static native String GetCity(long I);
	public final static native String GetCityAbbreviation(long I);
	public final static native String GetState(long I);
	public final static native String GetZip(long I);
	public final static native String GetPlus4(long I);
	public final static native String GetCarrierRoute(long I);
	public final static native String GetDeliveryPointCode(long I);
	public final static native String GetDeliveryPointCheckDigit(long I);
	public final static native String GetCountyFips(long I);
	public final static native String GetCountyName(long I);
	public final static native String GetAddressTypeCode(long I);
	public final static native String GetAddressTypeString(long I);
	public final static native String GetUrbanization(long I);
	public final static native String GetCongressionalDistrict(long I);
	public final static native String GetLACS(long I);
	public final static native String GetLACSLinkIndicator(long I);
	public final static native String GetPrivateMailbox(long I);
	public final static native String GetTimeZoneCode(long I);
	public final static native String GetTimeZone(long I);
	public final static native String GetMsa(long I);
	public final static native String GetPmsa(long I);
	public final static native String GetDefaultFlagIndicator(long I);
	public final static native String GetSuiteStatus(long I);
	public final static native String GetEWSFlag(long I);
	public final static native String GetCMRA(long I);
	public final static native String GetDsfVacant(long I);
	public final static native String GetCountryCode(long I);
	public final static native String GetZipType(long I);
	public final static native String GetFalseTable(long I);
	public final static native String GetDPVFootnotes(long I);
	public final static native String GetLACSLinkReturnCode(long I);
	public final static native String GetSuiteLinkReturnCode(long I);
	public final static native String GetRBDI(long I);
	public final static native String GetELotNumber(long I);
	public final static native String GetELotOrder(long I);
	public final static native String GetAddressKey(long I);
	public final static native String GetMelissaAddressKey(long I);
	public final static native String GetMelissaAddressKeyBase(long I);
	public final static native String GetOutputParameter(long I,String p1);
	public final static native int SetInputParameter(long I,String p1,String p2);
	public final static native boolean FindSuggestion(long I);
	public final static native boolean FindSuggestionNext(long I);
	public final static native String GetDsfNoStats(long I);
	public final static native String GetDsfDNA(long I);
	public final static native int GetPS3553_B6_TotalRecords(long I);
	public final static native int GetPS3553_C1a_ZIP4Coded(long I);
	public final static native int GetPS3553_C1c_DPBCAssigned(long I);
	public final static native int GetPS3553_C1d_FiveDigitCoded(long I);
	public final static native int GetPS3553_C1e_CRRTCoded(long I);
	public final static native int GetPS3553_C1f_eLOTAssigned(long I);
	public final static native int GetPS3553_E_HighRiseDefault(long I);
	public final static native int GetPS3553_E_HighRiseExact(long I);
	public final static native int GetPS3553_E_RuralRouteDefault(long I);
	public final static native int GetPS3553_E_RuralRouteExact(long I);
	public final static native int GetZip4HRDefault(long I);
	public final static native int GetZip4HRExact(long I);
	public final static native int GetZip4RRDefault(long I);
	public final static native int GetZip4RRExact(long I);
	public final static native int GetPS3553_E_LACSCount(long I);
	public final static native int GetPS3553_E_EWSCount(long I);
	public final static native int GetPS3553_E_DPVCount(long I);
	public final static native int GetPS3553_X_POBoxCount(long I);
	public final static native int GetPS3553_X_HCExactCount(long I);
	public final static native int GetPS3553_X_FirmCount(long I);
	public final static native int GetPS3553_X_GenDeliveryCount(long I);
	public final static native int GetPS3553_X_MilitaryZipCount(long I);
	public final static native int GetPS3553_X_NonDeliveryCount(long I);
	public final static native int GetPS3553_X_StreetCount(long I);
	public final static native int GetPS3553_X_HCDefaultCount(long I);
	public final static native int GetPS3553_X_OtherCount(long I);
	public final static native int GetPS3553_X_LacsLinkCodeACount(long I);
	public final static native int GetPS3553_X_LacsLinkCode00Count(long I);
	public final static native int GetPS3553_X_LacsLinkCode14Count(long I);
	public final static native int GetPS3553_X_LacsLinkCode92Count(long I);
	public final static native int GetPS3553_X_LacsLinkCode09Count(long I);
	public final static native int GetPS3553_X_SuiteLinkCodeACount(long I);
	public final static native int GetPS3553_X_SuiteLinkCode00Count(long I);
	public final static native String GetParsedAddressRange(long I);
	public final static native String GetParsedPreDirection(long I);
	public final static native String GetParsedStreetName(long I);
	public final static native String GetParsedSuffix(long I);
	public final static native String GetParsedPostDirection(long I);
	public final static native String GetParsedSuiteName(long I);
	public final static native String GetParsedSuiteRange(long I);
	public final static native String GetParsedPrivateMailboxName(long I);
	public final static native String GetParsedPrivateMailboxNumber(long I);
	public final static native String GetParsedGarbage(long I);
	public final static native String GetParsedRouteService(long I);
	public final static native String GetParsedLockBox(long I);
	public final static native String GetParsedDeliveryInstallation(long I);
	public final static native void SetReserved(long I,String p1,String p2);
	public final static native String GetReserved(long I,String p1);
}
